# Generated by Django 2.1.7 on 2022-06-28 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ped_id_UsuarioAutorizo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizador', to=settings.AUTH_USER_MODEL, verbose_name='Autorizador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ped_id_UsuarioCancelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelo', to=settings.AUTH_USER_MODEL, verbose_name='Cancelador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ped_id_UsuarioCreo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creador', to=settings.AUTH_USER_MODEL, verbose_name='Creador de pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ped_id_usr_descargo_excel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descargo', to=settings.AUTH_USER_MODEL, verbose_name='Descargo'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='dtl_creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='dtl_id_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.Pedido', verbose_name='Folio Pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='configrestriccion',
            unique_together={('conf_r_fecha_inicio', 'conf_r_fecha_fin', 'conf_r_tipo_pedido')},
        ),
    ]
