# Generated by Django 2.1.5 on 2019-03-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20190315_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ped_estatusPedido',
            field=models.IntegerField(choices=[(1, 'Pendiente por autorizar'), (2, 'Autorizado'), (3, 'Facturado'), (4, 'Rechazado'), (5, 'Entregado')], default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ped_fechaAutorizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de autorización'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ped_fechaCancelacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación'),
        ),
    ]
