# Generated by Django 2.1.7 on 2019-03-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_auto_20190315_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='dtl_tipo_pedido',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio')], default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='dtl_tipo_pedido',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio')], default=0),
        ),
    ]
