# Generated by Django 2.1.7 on 2019-03-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_auto_20190325_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion_pedido',
            fields=[
                ('conf_ID', models.AutoField(primary_key=True, serialize=False)),
                ('conf_fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('conf_fecha_fin', models.DateField(verbose_name='Fecha final')),
            ],
        ),
    ]
