# Generated by Django 2.1.7 on 2019-04-08 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_pedido_ped_autorizo_fuera_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion_pedido',
            name='conf_fecha_fin_autorizador',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha final para autorizar'),
        ),
    ]
