# Generated by Django 2.1.7 on 2019-05-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_configuracion_pedido_conf_fecha_fin_autorizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_tipo_insumo',
            field=models.IntegerField(choices=[(800044556, 'Insumos Pedido Mensual'), (800044563, 'Papeleria Pedido Mensual')], default=800044556),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_tipo',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza')], verbose_name='Tipo de producto'),
        ),
    ]
