# Generated by Django 2.1.7 on 2019-05-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0010_auto_20190522_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ped_v_limpieza',
            field=models.BooleanField(default=False, verbose_name='Visible en Limpieza'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ped_v_limpieza_consultorio',
            field=models.BooleanField(default=False, verbose_name='Visible en Limpieza Consultorio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ped_v_papeleria',
            field=models.BooleanField(default=False, verbose_name='Visible en papeleria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_tipo',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio')], verbose_name='Tipo de producto'),
        ),
    ]
