# Generated by Django 2.1.7 on 2019-05-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_auto_20190527_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='ped_v_limpieza',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_v_limpieza_consultorio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_v_papeleria',
        ),
        migrations.AddField(
            model_name='producto',
            name='prod_v_limpieza',
            field=models.BooleanField(default=False, verbose_name='Visible en Limpieza'),
        ),
        migrations.AddField(
            model_name='producto',
            name='prod_v_limpieza_consultorio',
            field=models.BooleanField(default=False, verbose_name='Visible en Limpieza Consultorio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='prod_v_papeleria',
            field=models.BooleanField(default=False, verbose_name='Visible en papeleria'),
        ),
    ]
