# Generated by Django 2.1.7 on 2019-06-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_auto_20190527_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ped_fechaCreacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
