# Generated by Django 2.1.7 on 2019-05-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_auto_20190527_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prod_v_consumibles',
            field=models.BooleanField(default=False, verbose_name='Visible en consumibles'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_tipo',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Consumibles')], verbose_name='Tipo de producto'),
        ),
    ]
