# Generated by Django 2.1.7 on 2019-06-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0013_auto_20190611_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prod_v_consumibles',
            field=models.BooleanField(default=False, verbose_name='Visible en consumibles'),
        ),
    ]
