# Generated by Django 2.1.7 on 2019-05-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0013_auto_20190531_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dtl_tipo_pedido',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Consumibles')], default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ped_fechaCreacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
