# Generated by Django 2.1.7 on 2019-06-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0013_auto_20190531_1124'),
        ('pedido', '0014_auto_20190531_1119'),
    ]

    operations = [
    ]
