# Generated by Django 2.1.7 on 2020-05-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0015_merge_20190617_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='dtl_tipo_pedido',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner')], default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dtl_tipo_pedido',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner')], default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_tipo',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner')], verbose_name='Tipo de producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_v_consumibles',
            field=models.BooleanField(default=False, verbose_name='Visible en Toner'),
        ),
    ]
