# Generated by Django 2.1.7 on 2020-09-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0016_auto_20200527_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pro_centrocosto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro de costo'),
        ),
    ]
