# Generated by Django 2.1.7 on 2021-02-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0017_producto_pro_centrocosto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='pro_centrocosto',
        ),
        migrations.AddField(
            model_name='producto',
            name='prod_v_papeleria_consultorio',
            field=models.BooleanField(default=False, verbose_name='Visible en papeleria Consultorio'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='dtl_tipo_pedido',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner'), (5, 'Papeleria consultorio')], default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dtl_tipo_pedido',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner'), (5, 'Papeleria consultorio')], default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_tipo',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner'), (5, 'Papeleria consultorio')], verbose_name='Tipo de producto'),
        ),
    ]
