# Generated by Django 2.1.7 on 2021-03-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0018_auto_20210225_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prod_v_toner_consultorio',
            field=models.BooleanField(default=False, verbose_name='Visible en Toner Consultorio'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='dtl_tipo_pedido',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner'), (5, 'Papeleria consultorio'), (6, 'Toner consultorio')], default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dtl_tipo_pedido',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner'), (5, 'Papeleria consultorio'), (6, 'Toner consultorio')], default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_tipo',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner'), (5, 'Papeleria consultorio'), (6, 'Toner consultorio')], verbose_name='Tipo de producto'),
        ),
    ]
