# Generated by Django 2.1.7 on 2021-12-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0020_auto_20210420_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigRestriccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_r_fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('conf_r_fecha_fin', models.DateField(verbose_name='Fecha final')),
                ('conf_r_tipo_pedido', models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner'), (5, 'Papeleria consultorio'), (6, 'Toner consultorio'), (7, 'Globos')], default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='configrestriccion',
            unique_together={('conf_r_fecha_inicio', 'conf_r_fecha_fin', 'conf_r_tipo_pedido')},
        ),
    ]
