# Generated by Django 2.1.7 on 2022-02-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0021_auto_20211218_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ped_entregado',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ped_fechaEntrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
    ]
