# Generated by Django 2.1.7 on 2022-03-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0022_auto_20220211_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prod_v_limpieza_oficina',
            field=models.BooleanField(default=False, verbose_name='Visible Limpieza oficina'),
        ),
    ]
