# Generated by Django 2.1.7 on 2022-03-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0023_producto_prod_v_limpieza_oficina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configrestriccion',
            name='conf_r_tipo_pedido',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner'), (5, 'Papeleria consultorio'), (6, 'Toner consultorio'), (7, 'Globos'), (8, 'Limpieza oficina')], default=0),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='dtl_tipo_pedido',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner'), (5, 'Papeleria consultorio'), (6, 'Toner consultorio'), (7, 'Globos'), (8, 'Limpieza oficina')], default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dtl_tipo_pedido',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner'), (5, 'Papeleria consultorio'), (6, 'Toner consultorio'), (7, 'Globos'), (8, 'Limpieza oficina')], default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_tipo',
            field=models.IntegerField(choices=[(1, 'Papeleria'), (2, 'Limpieza'), (3, 'Limpieza Consultorio'), (4, 'Toner'), (5, 'Papeleria consultorio'), (6, 'Toner consultorio'), (7, 'Globos'), (8, 'Limpieza oficina')], verbose_name='Tipo de producto'),
        ),
    ]
