# Generated by Django 2.1.7 on 2020-09-21 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('suc_id', models.AutoField(primary_key=True, serialize=False)),
                ('suc_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero sucursal')),
                ('suc_nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('suc_monto_papeleria', models.FloatField(verbose_name='Monto a comprar papeleria')),
                ('suc_monto_limpieza', models.FloatField(verbose_name='Monto a comprar limpieza')),
                ('suc_monto_limpieza_oficina', models.FloatField(default=0, verbose_name='Monto a comprar limpieza consultorio')),
                ('suc_monto_consumible', models.FloatField(default=0, verbose_name='Monto a comprar consumibles')),
                ('suc_direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Direccion de sucursal')),
                ('suc_razon_social', models.CharField(blank=True, max_length=350, null=True, verbose_name='Razon Social')),
                ('suc_cc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Centro de Costo')),
            ],
            options={
                'ordering': ('suc_nombre',),
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('zona_nombre',),
            },
        ),
        migrations.AddField(
            model_name='sucursal',
            name='suc_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Zona', verbose_name='Pertenece zona'),
        ),
    ]
