# Generated by Django 2.1.7 on 2019-03-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('suc_id', models.AutoField(primary_key=True, serialize=False)),
                ('suc_nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('suc_monto_papeleria', models.FloatField(verbose_name='Monto a comprar papeleria')),
                ('suc_monto_limpieza', models.FloatField(verbose_name='Monto a comprar limpieza')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='sucursal',
            name='suc_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Zona', verbose_name='Pertenece zona'),
        ),
    ]
