# Generated by Django 2.1.7 on 2019-03-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='suc_monto_limpieza_oficina',
            field=models.FloatField(default=0, verbose_name='Monto a comprar limpieza oficina'),
        ),
    ]
