# Generated by Django 2.1.7 on 2019-04-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_sucursal_suc_monto_limpieza_oficina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ('suc_nombre',)},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ('zona_nombre',)},
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='suc_monto_limpieza_oficina',
            field=models.FloatField(default=0, verbose_name='Monto a comprar limpieza consultorio'),
        ),
    ]
