# Generated by Django 2.1.7 on 2019-05-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20190401_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='suc_direccion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre'),
        ),
    ]
