# Generated by Django 2.1.7 on 2019-05-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_sucursal_suc_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='suc_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='suc_direccion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Direccion de sucursal'),
        ),
    ]
