# Generated by Django 2.1.7 on 2019-06-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20190522_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='suc_monto_consumible',
            field=models.FloatField(default=0, verbose_name='Monto a comprar consumibles'),
        ),
    ]
