# Generated by Django 2.1.7 on 2020-05-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_sucursal_suc_monto_consumible'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='suc_razon_social',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Razon Social'),
        ),
    ]
