# Generated by Django 2.1.7 on 2020-09-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_sucursal_suc_razon_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='suc_cc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Centro de Costo'),
        ),
    ]
