# Generated by Django 2.1.7 on 2020-11-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_sucursal_suc_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='suc_zona_str',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zona sucursal'),
        ),
    ]
