# Generated by Django 2.1.7 on 2021-02-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_sucursal_suc_zona_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='suc_monto_papeleria_consultorio',
            field=models.FloatField(default=0, verbose_name='Monto a comprar papeleria consultorio'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='suc_zona_str',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sucursal Ubictum'),
        ),
    ]
