# Generated by Django 2.1.7 on 2021-03-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_auto_20210225_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='suc_monto_toner_consultorio',
            field=models.FloatField(default=0, verbose_name='Monto a comprar toner consultorio'),
        ),
    ]
