# Generated by Django 2.1.7 on 2021-04-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_sucursal_suc_monto_toner_consultorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='suc_monto_globos',
            field=models.FloatField(default=0, verbose_name='Monto a comprar globos'),
        ),
    ]
