# Generated by Django 2.1.7 on 2022-03-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0012_sucursal_suc_monto_globos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='suc_monto_limpieza_oficina_v',
            field=models.FloatField(default=0, verbose_name='Monto a comprar limpieza oficina'),
        ),
    ]
