# Generated by Django 2.1.7 on 2019-03-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('usuario', '0002_auto_20190314_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suc_pertene',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.Sucursal', verbose_name='Sucursal pertenece usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='zona_pertene',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.Zona', verbose_name='Zona pertenece supervisor'),
        ),
    ]
