# Generated by Django 2.1.7 on 2019-03-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20190314_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_user',
            field=models.IntegerField(choices=[(1, 'Supervisor'), (2, 'Asesor'), (3, 'Usuario')], default=1),
        ),
    ]
