# Generated by Django 2.1.7 on 2019-03-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20190315_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_user',
            field=models.IntegerField(choices=[(1, 'Supervisor'), (2, 'Asesor'), (3, 'Usuario')], default=3),
        ),
    ]
