# Generated by Django 2.1.7 on 2019-03-26 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20190315_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='suc_pertene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.Sucursal', verbose_name='Sucursal pertenece usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zona_pertene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.Zona', verbose_name='Zona pertenece supervisor'),
        ),
    ]
